// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GQCreateExample struct {
	Variable1 string `json:"variable1"`
	Variable2 int    `json:"variable2"`
}

type GQExample struct {
	ID        string `json:"id"`
	Variable1 string `json:"variable1"`
	Variable2 int    `json:"variable2"`
}

type GQUpdateExample struct {
	ID        string `json:"id"`
	Variable1 string `json:"variable1"`
	Variable2 int    `json:"variable2"`
}
